# Generated by Django 5.2 on 2026-04-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Items de Checklist',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_area', models.CharField(max_length=200)),
                ('responsable_area', models.CharField(max_length=200)),
                ('tecnico_nombre', models.CharField(max_length=200)),
                ('fecha_ejecucion', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('actividades_realizadas', models.TextField(blank=True)),
                ('materiales_utilizados', models.TextField(blank=True)),
                ('estado_equipo_post', models.CharField(blank=True, choices=[('OPERATIVO', 'Operativo'), ('OPERATIVO_OBSERVACIONES', 'Operativo con observaciones'), ('NO_OPERATIVO', 'No operativo')], max_length=30)),
                ('observaciones_tecnico', models.TextField(blank=True)),
                ('riesgo_presentado', models.BooleanField(default=False)),
                ('descripcion_riesgo', models.TextField(blank=True)),
                ('acciones_tomadas', models.TextField(blank=True)),
                ('fecha_sugerida_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE_FIRMA_TECNICO', 'Pendiente firma técnico'), ('PENDIENTE_FIRMA_USUARIO', 'Pendiente firma usuario'), ('COMPLETADO', 'Completado')], default='BORRADOR', max_length=30)),
                ('documento_pdf', models.FileField(blank=True, null=True, upload_to='documentos/mantenimientos/')),
                ('documento_pdf_generado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='equipos.equipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_ejecucion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_firma', models.CharField(choices=[('TECNICO', 'Técnico'), ('USUARIO', 'Usuario')], max_length=10)),
                ('nombre_firmante', models.CharField(max_length=200)),
                ('cargo_firmante', models.CharField(blank=True, max_length=200)),
                ('firma_imagen', models.ImageField(upload_to='firmas/')),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas', to='mantenimientos.mantenimiento')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmas',
                'unique_together': {('mantenimiento', 'tipo_firma')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='mantenimientos.checklistitem')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_respuestas', to='mantenimientos.mantenimiento')),
            ],
            options={
                'verbose_name': 'Respuesta de Checklist',
                'verbose_name_plural': 'Respuestas de Checklist',
                'unique_together': {('mantenimiento', 'checklist_item')},
            },
        ),
    ]
