# Generated by Django 5.2 on 2026-04-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
