# Generated by Django 5.2 on 2026-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('tipo_equipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop'), ('IMPRESORA', 'Impresora'), ('SERVIDOR', 'Servidor'), ('MONITOR', 'Monitor'), ('OTRO', 'Otro')], max_length=50)),
                ('ubicacion', models.CharField(max_length=200)),
                ('colaborador_nombre', models.CharField(max_length=200)),
                ('colaborador_correo', models.EmailField(blank=True, max_length=254)),
                ('colaborador_puesto', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('motivo_baja', models.TextField(blank=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['codigo_interno'],
            },
        ),
    ]
