# Generated by Django 5.2 on 2026-04-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='motivo_baja',
            field=models.TextField(blank=True, null=True),
        ),
    ]
